#!/usr/bin/env python3

import getpass
from twilio.rest import Client
import subprocess
#from pyfiglet import Figlet
subprocess.run(['clear'])

print('''
               _     __        _             
 ____ __  ___ | |__ /  \ _ __ | |__  ___ _ _ 
(_-< '  \(_-< | '_ \ () | '  \| '_ \/ -_) '_|
/__/_|_|_/__/ |_.__/\__/|_|_|_|_.__/\___|_|
''')

# f = Figlet(font='small')
#print(f.renderText('sms b0mber'))
# subprocess.run(['figlet sms b0mber'])

acctSID = getpass.getpass('AccountSID: ')
authToken = getpass.getpass('Auth token: ')
recipient = input('Recipient 11 digit phone number: ')
sender = input('Sender 11 digit phone number: ')
msg = input('Enter message: ')
num_texts = int(input('Number of texts: '))

x = 0
while x < num_texts:
    account_sid = acctSID
    auth_token = authToken

    client = Client(account_sid, auth_token)

    message = client.messages.create(
        to="+" + recipient,
        from_="+" + sender,
        body = msg)
    print(message.sid)
    x += 1
